Document: wlmessage
Title: Debian wlmessage Manual
Author: <insert document author here>
Abstract: This manual describes what wlmessage is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/wlmessage/wlmessage.sgml.gz

Format: postscript
Files: /usr/share/doc/wlmessage/wlmessage.ps.gz

Format: text
Files: /usr/share/doc/wlmessage/wlmessage.text.gz

Format: HTML
Index: /usr/share/doc/wlmessage/html/index.html
Files: /usr/share/doc/wlmessage/html/*.html
